# nixpacks.toml

# Définir le runtime comme PHP
[phases.setup]
runtime = "php"

# Installer Composer et les extensions PHP nécessaires
[phases.setup]
commands = [
    "php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\"",
    "php composer-setup.php --install-dir=/usr/local/bin --filename=composer",
    "php -r \"unlink('composer-setup.php');\"",
    "composer install --no-dev --optimize-autoloader"
]

# Phase de build pour optimiser l'autoload
[phases.build]
commands = [
    "composer dump-autoload --optimize"
]

# Phase de démarrage pour lancer le serveur PHP
[phases.start]
commands = [
    "php -S 0.0.0.0:8080 -t public"
]

# Packages nécessaires
[phases.setup]
packages = [
    "php",
    "php-pdo",
    "php-mbstring"
]
